package consts

const (
	VALIDATION_ERROR_CODE      string = "VALIDATION_ERROR"
	INTERNAL_SERVER_ERROR_CODE string = "INTERNAL_SERVER_ERROR"
	UNAUTHORIZED_ERROR         string = "UNAUTHORIZED_ERROR"
)
